import json
import os
import sys

FIRMWARE_DIR_NAME = "arduino_firmware"

def generate_arduino_header(json_filename="settings.json", header_filename="config.h"):
    # 実行ファイル（main.pyまたはexe）と同じ場所にあるJSONを探す
    if getattr(sys, 'frozen', False):
        application_path = os.path.dirname(sys.executable) # .exe
    else:
        application_path = os.path.dirname(os.path.abspath(__file__)) # .py
    
    json_path = os.path.join(application_path, json_filename)

    firmware_dir = os.path.join(application_path, FIRMWARE_DIR_NAME)

    # ディレクトリがなければ作る
    if not os.path.exists(firmware_dir):
        try:
            os.makedirs(firmware_dir)
            print(f"[Info] Created directory: {firmware_dir}")
        except OSError as e:
            print(f"[Error] Could not create directory '{firmware_dir}': {e}")
            return

    header_path = os.path.join(firmware_dir, header_filename)

    # ファイルの存在確認
    if not os.path.exists(json_path):
        print(f"[Error] Configuration file not found: {json_path}")
        return

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"[Error] Invalid JSON format in {json_path}:\n{e}")
        return

    # データの抽出
    sys_conf = data.get("system", {})
    pins_conf = data.get("pins", {})
    cells = data.get("cells", {})
    servos = data.get("servos", {})
    safety = data.get("safety", {})

    # 排他ペア
    exclusive_pairs = []
    
    # 電極タイプごとにピンをまとめる
    electrodes_by_type = {} 
    for cell_name, pins in cells.items():
        for elec_type, pin in pins.items():
            if elec_type not in electrodes_by_type:
                electrodes_by_type[elec_type] = []
            electrodes_by_type[elec_type].append(pin)
    # 総当たりでペア生成
    for elec_type, pins in electrodes_by_type.items():
        pins_sorted = sorted(list(set(pins))) # 重複排除とソート
        for i in range(len(pins_sorted)):
            for j in range(i + 1, len(pins_sorted)):
                exclusive_pairs.append((pins_sorted[i], pins_sorted[j]))

    # サーボのデフォルト（オフ）角度
    servo_defaults = []
    for name, settings in servos.items():
        pin = settings.get("pin")
        off_angle = settings.get("off_angle", 0) # 設定がなければ0度
        servo_defaults.append((pin, off_angle))

    # システムピン
    pin_start = pins_conf.get("start", -1)
    pin_estop = pins_conf.get("estop", -1)

    # 使用ピンのリスト
    valid_pins = set()
    # 電極
    for cell in cells.values():
        for pin in cell.values():
            valid_pins.add(pin)  
    # サーボ
    for s in servos.values():
        valid_pins.add(s['pin'])
    # システムピン（Start/Estopなど）
    for pin in pins_conf.values():
         if isinstance(pin, int) and pin > 0: valid_pins.add(pin)
    valid_pin_list = sorted(list(valid_pins))

    # C++ヘッダー書き出し

    lines = []
    lines.append("// This file is AUTO-GENERATED by update_config.py")
    lines.append("// DO NOT EDIT MANUALLY")
    lines.append(f"// Source: {json_filename}")
    lines.append("")
    lines.append("#ifndef CONFIG_H")
    lines.append("#define CONFIG_H")
    lines.append("")

    # ボーレート (main.pyと同じデフォルト値 9600 を採用)
    baud = sys_conf.get("baudrate", 9600)
    lines.append(f"const long BAUDRATE = {baud};")

    # システムピン
    lines.append("")
    lines.append("// --- System Control Pins ---")
    lines.append(f"const int PIN_START = {pin_start};")
    lines.append(f"const int PIN_ESTOP = {pin_estop};")
    
    # 排他ペア配列生成
    lines.append("")
    lines.append("// --- Safety Interlock Pairs ---")
    lines.append(f"const int PAIR_COUNT = {len(exclusive_pairs)};")
    if len(exclusive_pairs) > 0:
        lines.append("const int EXCLUSIVE_PAIRS[][2] = {")
        for i, (p1, p2) in enumerate(exclusive_pairs):
            suffix = "," if i < len(exclusive_pairs) - 1 else "" # 最後の行以外は,をつける
            lines.append(f"  {{ {p1}, {p2} }}{suffix} // Pair {i+1}") # C++の配列表記に整形（例: { 2, 8 },）
        lines.append("};")
    else:
        # 排他ペアがなかった場合、コンパイルエラー防止のダミー
        lines.append("const int EXCLUSIVE_PAIRS[1][2] = {{ -1, -1 }};")

    # サーボのデフォルト角度配列生成
    lines.append("")
    lines.append("// --- Servo Default (Safe) Angles ---")
    lines.append(f"const int SERVO_COUNT_DEF = {len(servo_defaults)};")
    if len(servo_defaults) > 0:
        lines.append("const int SERVO_DEFAULTS[][2] = {")
        for i, (pin, angle) in enumerate(servo_defaults):
            suffix = "," if i < len(servo_defaults) - 1 else ""
            lines.append(f"  {{ {pin}, {angle} }}{suffix} // Pin {pin} -> {angle} deg")
        lines.append("};")
    else:
        lines.append("const int SERVO_DEFAULTS[1][2] = {{ -1, 0 }};")

    # 使用ピン配列生成
    lines.append("")
    lines.append("// --- Valid Pins (Whitelist) ---")
    lines.append(f"const int VALID_PIN_COUNT = {len(valid_pin_list)};")
    if len(valid_pin_list) > 0:
        # C++配列: const int VALID_PINS[] = { 2, 3, 4, ... };
        pins_str = ", ".join(map(str, valid_pin_list))
        lines.append(f"const int VALID_PINS[] = {{ {pins_str} }};")
    else:
        lines.append("const int VALID_PINS[] = { -1 };")

    # ウォッチドッグタイマー設定
    wd_timeout = safety.get("watchdog_timeout_ms", 3000) # デフォルト3000ms
    lines.append("")
    lines.append("// --- Safety Settings ---")
    lines.append(f"const long WATCHDOG_TIMEOUT = {wd_timeout};") # const longとして出力

    lines.append("")
    lines.append("#endif // CONFIG_H")

    # 書き込み
    try:
        with open(header_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        print(f"[Success] Generated '{header_filename}' from '{json_filename}'")
        print(f" - Path: {header_path}")
        print(f" - Exclusive Pairs: {len(exclusive_pairs)}")
        print("Please upload this config to Arduino now.")
        
    except Exception as e:
        print(f"[Error] Failed to write header file:\n{e}")

if __name__ == "__main__":
    generate_arduino_header()